Repository mocks-server/website, pull requests merged in 2019-11, with the labels that each got.

#9 Code highlighting
  docs/advanced-programmatic-usage.md
  docs/configuration-command-line-arguments.md
  docs/get-started-behaviors.md
  docs/get-started-fixtures.md
  docs/get-started-intro.md
  docs/tutorials-dynamic.md
  docs/tutorials-static.md
  docs/welcome-about-docs.md
  website/siteConfig.js
  website/static/css/code-block-buttons.css
  website/static/js/code-block-buttons.js
Labels: documentation

#17 Add Algolia search bar configuration
  website/siteConfig.js
Labels: enhancement

#11 Added a fix to "extending behaviors" code example
  docs/get-started-behaviors.md
Labels: bug, documentation

#18 Minor fixes
  docs/advanced-programmatic-usage.md
  docs/get-started-intro.md
  website/pages/en/users.js
  website/siteConfig.js
  website/users.js
Labels: bug, documentation

#21 Add versioning
  website/pages/en/index.js
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-1.3.0/advanced-programmatic-usage.md
  website/versioned_docs/version-1.3.0/configuration-command-line-arguments.md
  website/versioned_docs/version-1.3.0/configuration-interactive-cli.md
  website/versioned_docs/version-1.3.0/configuration-rest-api.md
  website/versioned_docs/version-1.3.0/get-started-behaviors.md
  website/versioned_docs/version-1.3.0/get-started-fixtures.md
  website/versioned_docs/version-1.3.0/get-started-intro.md
  website/versioned_docs/version-1.3.0/integrations-end-to-end-testing.md
  website/versioned_docs/version-1.3.0/integrations-local-development.md
  website/versioned_docs/version-1.3.0/tutorials-dynamic.md
  website/versioned_docs/version-1.3.0/tutorials-static.md
  website/versioned_docs/version-1.3.0/welcome-about-docs.md
  website/versioned_sidebars/version-1.3.0-sidebars.json
  website/versions.json
Labels: documentation, enhancement
